import { cpSync, existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { PlopTypes } from "@turbo/gen";

/**
 * `turbo gen app` — stamp a new app as a copy of apps/web AS IT IS NOW
 * (copy-live, so the generator never drifts from the reference app).
 *
 * Defaults to the shared-product model: same Clerk applications, same
 * Supabase databases, same Proton Pass secret items as web (per AGENTS.md,
 * app-private tables would go in an app-specific schema). The new app gets
 * its own portless hostname, Vercel project, and VITE_PUBLIC_APP_URL.
 */

const EXCLUDE = new Set([
  "node_modules",
  "dist",
  ".output",
  ".nitro",
  ".tanstack",
  ".vercel",
  ".clerk",
  ".env.local",
  "routeTree.gen.ts", // regenerated by tsr
  "README.md", // the generator writes its own
]);
const EXCLUDE_SUFFIXES = [".secrets"];
const EXCLUDE_PATHS = [
  "src/routes/api/webhooks", // the Clerk mirror sync has exactly one consumer: web
];

function walk(dir: string, base: string, out: string[]): void {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = relative(base, full);
    if (EXCLUDE.has(entry)) continue;
    if (EXCLUDE_SUFFIXES.some((s) => entry.endsWith(s))) continue;
    if (entry.endsWith(".local") && entry.startsWith(".env")) continue;
    if (EXCLUDE_PATHS.some((p) => rel === p || rel.startsWith(`${p}/`))) continue;
    if (statSync(full).isDirectory()) walk(full, base, out);
    else out.push(rel);
  }
}

export default function generator(plop: PlopTypes.NodePlopAPI): void {
  plop.setActionType("copy-web-app", (answers) => {
    const { name } = answers as { name: string };
    const repoRoot = join(__dirname, "../..");
    const srcApp = join(repoRoot, "apps/web");
    const destApp = join(repoRoot, "apps", name);
    if (existsSync(destApp)) throw new Error(`apps/${name} already exists`);

    const files: string[] = [];
    walk(srcApp, srcApp, files);

    for (const rel of files) {
      const from = join(srcApp, rel);
      const to = join(destApp, rel);
      const isText = !/\.(png|jpg|jpeg|ico|woff2?)$/.test(rel);
      if (!isText) {
        cpSync(from, to, { recursive: true });
        continue;
      }
      let txt = readFileSync(from, "utf8");
      // app identity: portless hostname + package name
      txt = txt.replaceAll("app.archipelago", `${name}.archipelago`);
      txt = txt.replace('"name": "web"', `"name": "${name}"`);
      if (rel === ".env.staging" || rel === ".env.production") {
        // per-app deployment origin: unknown until this app's Vercel project exists
        txt = txt.replace(
          /^VITE_PUBLIC_APP_URL=.*$/m,
          "# TODO: set to this app's deployment origin once its Vercel project exists\nVITE_PUBLIC_APP_URL=",
        );
      }
      cpSync(from, to); // creates parent dirs
      writeFileSync(to, txt);
    }
    return `apps/${name}: ${files.length} files stamped from apps/web`;
  });

  plop.setGenerator("app", {
    description: "New app stamped from apps/web (shared auth, DBs, and secrets)",
    prompts: [
      {
        type: "input",
        name: "name",
        message: "App name (kebab-case, becomes apps/<name> and <name>.archipelago.localhost):",
        validate: (input: string) => {
          if (!/^[a-z][a-z0-9-]*$/.test(input)) return "kebab-case, starting with a letter";
          if (input === "web") return "web already exists";
          return true;
        },
      },
    ],
    actions: [
      { type: "copy-web-app" },
      {
        type: "add",
        path: "{{ turbo.paths.root }}/apps/{{ name }}/README.md",
        template: `# {{ name }}

Stamped from \`apps/web\` by \`turbo gen app\`. Shares the product's Clerk
applications, Supabase databases, and Proton Pass secret items (see AGENTS.md;
app-private tables belong in an app-specific DB schema).

## Remaining setup

1. \`bun install\` (links workspace deps and bins)
2. \`bun dev\` inside this app serves http://{{ name }}.archipelago.localhost
3. Vercel: \`bunx vercel@latest link --yes --project archipelago-{{ name }}\` from this
   directory, connect the Git repo in the dashboard (root directory
   \`apps/{{ name }}\`), then fill VITE_PUBLIC_APP_URL in .env.staging/.env.production
   and run \`bun run env:sync:staging\` / \`bun run env:sync:prod\`
4. Add this app's staging/production origins to the Clerk applications if it
   serves auth flows
`,
      },
      () => "Done. See apps/<name>/README.md for the remaining setup steps.",
    ],
  });
}
